version: '3.8'
services:
  backend:
    build: ./backend_nomongo
    container_name: hydra-backend
    restart: always
    environment:
      - PORT=5000
    expose:
      - "5000"
  caddy:
    image: caddy:2
    container_name: hydra-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
volumes:
  caddy_data:
  caddy_config:
